services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 10

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    env_file:
      - ./user-service/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "3001:3001"

  vehicle-service:
    build:
      context: ./vehicle-service
    container_name: vehicle-service
    env_file:
      - ./vehicle-service/.env
    depends_on:
      rabbitmq:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    env_file:
      - ./frontend/.env
    depends_on:
      - user-service
    ports:
      - "3000:3000"
